### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined     at Object.module.exports.generate 

### ISSUE THREAD

**Issue by dmiorandi** [syple/generator-ramlang#6]
I've got error in subject trying to generate raml. On the same file I can run official raml-client-generator and raml-to-jaxrs without any issue.

This is yo chat:

``` text
Welcome to RAMLang!!!

? What would you like to call the module: ams

Angular application module name: ams
Chosen RAML file:  api.raml

util.print: Use console.log instead
Reading RAML fileutil.print: Use console.log instead
 ✔

? Select which media type extension to use: (Use arrow keys)
? Select which media type extension to use: json
? Would you like to generate all resources: No
? Select which resources you want to generate: (Press <space> to select)
? Select which resources you want to generate:
? Should I generate all the resources in one file: Yes
? Generate all files in the current directory: Yes

Generating resources
C:\Users\Denis\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.js:579
    throw e;
          ^
TypeError: Cannot read property 'replace' of undefined
    at Object.module.exports.generate (C:\Users\Denis\AppData\Roaming\npm\node_modules\generator-ramlang\lib\provider.js:20:31)
    at Generator.generate (C:\Users\Denis\AppData\Roaming\npm\node_modules\generator-ramlang\app\index.js:415:39)
    at C:\Users\Denis\AppData\Roaming\npm\node_modules\generator-ramlang\node_modules\yeoman-generator\lib\base.js:341:43
    at C:\Users\Denis\AppData\Roaming\npm\node_modules\generator-ramlang\node_modules\yeoman-generator\node_modules\async\lib\async.js:551:21
    at C:\Users\Denis\AppData\Roaming\npm\node_modules\generator-ramlang\node_modules\yeoman-generator\node_modules\async\lib\async.js:227:13
    at iterate (C:\Users\Denis\AppData\Roaming\npm\node_modules\generator-ramlang\node_modules\yeoman-generator\node_modules\async\lib\async.js:134:13)
    at C:\Users\Denis\AppData\Roaming\npm\node_modules\generator-ramlang\node_modules\yeoman-generator\node_modules\async\lib\async.js:145:25
    at C:\Users\Denis\AppData\Roaming\npm\node_modules\generator-ramlang\node_modules\yeoman-generator\node_modules\async\lib\async.js:229:17
    at C:\Users\Denis\AppData\Roaming\npm\node_modules\generator-ramlang\node_modules\yeoman-generator\node_modules\async\lib\async.js:556:34
    at C:\Users\Denis\AppData\Roaming\npm\node_modules\generator-ramlang\node_modules\yeoman-generator\lib\base.js:327:11
```

**Comment by rafaelhoff** [comment]
I had the same issue. The problem occurred because a baseUri was not defined in my RAML.
The error disappears after setting one baseUri.

Anyway, it would be better to have an error message displayed.
